### ISSUE TITLE
What about using libyui? TUI+GUI in one!

### ISSUE THREAD

**Issue by timofonic** [1shad/pstreamer#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by 1shad** [comment]
Hello
Thanks for your interest.

I discover with your request this library.
After a quick glance, it seems interesting.
I could find [here](https://github.com/libyui/libyui-bindings/tree/master/swig/perl/examples), some snippets.

As soon as I had more time, I would look more in depth,
How to use it, and what is possible to do with it.
I would adapt the code in case.

Do not hesitate to propose a patch if you can.

Best regards

**Comment by 1shad** [comment]
Hello

After trying Libyui, I decided not to use it.

The fact that it is not packaged for several systems, and that it requires ruby and gem to compile it, makes installation difficult for end users.

And, I find that the different interfaces require different interactions. That it becomes difficult to manage with libyui.

You convinced me that a GUI could be interesting in some cases of use. So I decided to make a Gtk3 frontend, hoping that it will fill this gap.

You can use it in the new version with the --gtk option.

Have a nice day.
Cheers
